kumuluzee:
  name: rezervacije-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8082
    http:
      port: 8082
  datasources:
    - jndi-name: jdbc/RezervacijeMetadataDS
      connection-url: jdbc:postgresql://rezervacije-db.postgres.database.azure.com:5432/postgres?user=postgresAdmin&password=&sslmode=require
      username: postgresAdmin
  health:
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/RezervacijeMetadataDS
    metrics:
      web-instrumentation:
        - name: rezervacije-endpoint
          url-pattern: /v1/rezervacije/*
    rest-client:
      registrations:
        - class: rezervacije-processing-api
          url: http://localhost:8082/v1
          read-timeout: 5000
rest-properties:
  maintenance-mode: false
  broken: false
app-properties:
  amazon-rekognition:
    access-key:
    secret-key: