kumuluzee:
  name: rezervacije-service
  env:
    name: dev
  version: 1.0.0
  cors-filter:
    annotations:
      my-resource:
        allow-origin: "http://kumuluz.com"
        allow-subdomains: false
  server:
    base-url: http://localhost:8082
    http:
      port: 8082
  datasources:
    - jndi-name: jdbc/RezervacijeMetadataDS
      connection-url: jdbc:postgresql://localhost:5432/postgres
      username: postgres
      password: postgres
  health:
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/RezervacijeMetadataDS
    metrics:
      web-instrumentation:
        - name: rezervacije-endpoint
          url-pattern: /v1/rezervacije/*
    rest-client:
      registrations:
        - class: rezervacije-processing-api
          url: http://localhost:8082/v1
          read-timeout: 5000
rest-properties:
  maintenance-mode: false
  broken: false
app-properties:
  amazon-rekognition:
    access-key:
    secret-key:

igrisca-storitev:
  url: "http://20.85.139.182:8080/"
  enabled: false
  watch: true