kumuluzee:
  name: rezervacije-service
  env:
    name: dev
  version: 1.0.0
  cors-filter:
    annotations:
      my-resource:
        allow-origin: "http://kumuluz.com"
        allow-subdomains: false
  server:
    base-url: https://52.151.211.52:8082
    http:
      port: 8082
  datasources:
    - jndi-name: jdbc/RezervacijeMetadataDS
      connection-url: jdbc:postgresql://localhost:5432/postgres
      username: postgres
      password: postgres
  health:
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/RezervacijeMetadataDS
    metrics:
      web-instrumentation:
        - name: rezervacije-endpoint
          url-pattern: /v1/rezervacije/*
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                          <Configuration name="comments">
                              <Appenders>
                                  <Console name="console" target="SYSTEM_OUT">
                                      <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                                  </Console>
                                  <Socket name="logstash" host="b018540f-f4da-408b-afe6-d9e1251ff783-ls.logit.io"
                                  port="24836" protocol="udp">
                                      <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                                  </Socket>
                              </Appenders>
                              <Loggers>
                                  <!-- Default logger -->
                                  <Root level="all">
                                      <AppenderRef ref="console" level="info" />
                                      <AppenderRef ref="logstash" level="trace" />
                                  </Root>
                              </Loggers>
                          </Configuration>'
    rest-client:
      registrations:
        - class: rezervacije-processing-api
          url: https://localhost:8082/v1
          read-timeout: 5000
rest-properties:
  maintenance-mode: false
  broken: false
app-properties:
  amazon-rekognition:
    access-key:
    secret-key:

igrisca-storitev:
  url: "https://20.85.139.182:8080/"
  enabled: false
  watch: true

uporabniki-storitev:
  url: "https://20.85.248.6:8083/"
  enabled: false
  watch: true